# Maven
# Build your Java project and run tests with Apache Maven.
# Add steps that analyze code, save build artifacts, deploy, and more:
# https://docs.microsoft.com/azure/devops/pipelines/languages/java

trigger:
- main

pool:
  vmImage: windows-latest

steps:
- task: Maven@3
  inputs:
    mavenPomFile: 'pom.xml'
    mavenOptions: '-Xmx3072m'
    javaHomeOption: 'JDKVersion'
    jdkVersionOption: '1.8'
    jdkArchitectureOption: 'x64'
    publishJUnitResults: true
    testResultsFiles: '**/surefire-reports/TEST-*.xml'
    codeCoverageToolOption: 'Cobertura'
    codeCoverageFailIfEmpty: true
    codeCoverageRestoreOriginalPomXml: true
    goals: 'package'

- task: PublishBuildArtifacts@1
  displayName: 'Publish Artifact: drop'
  inputs:
    PathtoPublish: '$(build.artifactstagingdirectory)'

- task: SendEmail@1
  inputs:
    To: 'ankit.kumar@infostride.com'
    CC: 'saurav.sharma@infostride.com, abhishek.rawat@infostride.com'
    From: 'ankit.kumar@infostride.com'
    Subject: 'pipleine'
    Body: 'Hi, These are the reports'
    BodyAsHtml: false
    AddAttachment: true
    Attachment: '$(System.DefaultWorkingDirectory)/target/Extent-Reports/index.html'
    SmtpServer: 'smtp.office365.com'
    SmtpUsername: 'ankit.kumar@infostride.com'
    SmtpPassword: 'INFO7184@Ak'